name: Solutions for AdventJs Challenges

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.2.0'      
      - name: Install dependencies
        run: npm ci
      - name: Testing Challenge Solutions
        run: npm run test
